### ISSUE TITLE
Error raised on mouse cursor hover with matplotlib>=3.10

### ISSUE THREAD

**Issue by nvaytet** [matplotlib/ipympl#594]
## Describe the issue

Using `matplotlib>=3.10.*`, making any plot with `ipympl` raises an error when hovering the mouse over the axes.

Example:
```Py
import matplotlib.pyplot as plt
%matplotlib widget

fig, ax = plt.subplots()
```

Hovering the mouse over the plot raises
```
KeyError                                  Traceback (most recent call last)
File [~/miniforge3/lib/python3.12/site-packages/ipympl/backend_nbagg.py:278](http://localhost:8888/home/nvaytet/miniforge3/lib/python3.12/site-packages/ipympl/backend_nbagg.py#line=277), in Canvas._handle_message(self, object, content, buffers)
    275     self.manager.handle_json(content)
    277 else:
--> 278     self.manager.handle_json(content)

File [~/miniforge3/lib/python3.12/site-packages/matplotlib/backends/backend_webagg_core.py:474](http://localhost:8888/home/nvaytet/miniforge3/lib/python3.12/site-packages/matplotlib/backends/backend_webagg_core.py#line=473), in FigureManagerWebAgg.handle_json(self, content)
    473 def handle_json(self, content):
--> 474     self.canvas.handle_event(content)

File [~/miniforge3/lib/python3.12/site-packages/matplotlib/backends/backend_webagg_core.py:264](http://localhost:8888/home/nvaytet/miniforge3/lib/python3.12/site-packages/matplotlib/backends/backend_webagg_core.py#line=263), in FigureCanvasWebAggCore.handle_event(self, event)
    261 e_type = event['type']
    262 handler = getattr(self, f'handle_{e_type}',
    263                   self.handle_unknown_event)
--> 264 return handler(event)

File [~/miniforge3/lib/python3.12/site-packages/matplotlib/backends/backend_webagg_core.py:295](http://localhost:8888/home/nvaytet/miniforge3/lib/python3.12/site-packages/matplotlib/backends/backend_webagg_core.py#line=294), in FigureCanvasWebAggCore._handle_mouse(self, event)
    286 e_type = event['type']
    287 button = event['button'] + 1  # JS numbers off by 1 compared to mpl.
    288 buttons = {  # JS ordering different compared to mpl.
    289     button for button, mask in [
    290         (MouseButton.LEFT, 1),
    291         (MouseButton.RIGHT, 2),
    292         (MouseButton.MIDDLE, 4),
    293         (MouseButton.BACK, 8),
    294         (MouseButton.FORWARD, 16),
--> 295     ] if event['buttons'] & mask  # State *after* press[/release.](http://localhost:8888/release.)
    296 }
    297 modifiers = event['modifiers']
    298 guiEvent = event.get('guiEvent')

KeyError: 'buttons'
```

**Note:** need to set level to 'Debug' in log console to see it.

The figure is basically inactive.

Could be related to #592 but I did install `0.9.7` and it did not fix the issue.

Downgrading to `matplotlib=3.9.4` fixes the issue.

## Versions

```
 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
ipympl version: 0.9.7
Selected Jupyter core packages...
IPython          : 8.30.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.5
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.3.1
nbclient         : 0.10.1
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.14.3
```

**Comment by ianthomas23** [comment]
The symptoms are indeed the same as #592, and this has been fixed. I cannot reproduce with the same packages in a new environment:
```
ipympl                         0.9.7           pyhd8ed1ab_1          conda-forge
matplotlib                     3.10.1          py312h1f38498_0       conda-forge
Selected Jupyter core packages...
IPython          : 8.30.0
ipykernel        : 6.29.5
ipywidgets       : 8.1.5
jupyter_client   : 8.6.3
jupyter_core     : 5.7.2
jupyter_server   : 2.14.2
jupyterlab       : 4.3.1
nbclient         : 0.10.1
nbconvert        : 7.16.4
nbformat         : 5.10.4
notebook         : not installed
qtconsole        : not installed
traitlets        : 5.14.3
```
It looks you aren't actually using `ipympl 0.9.7` at runtime, even though that version is installed.

One report of this issue at matplotlib/matplotlib#29654 was that it was a caching issue which was solved by restarting the kernel a number of times. Please can you try that?

**Comment by T-Wainwright** [comment]
Getting the same issue with matplotlib 3.10.1, and ipympl 0.9.7, also setting the following behind the scenes to handle interactive figures:

```    
matplotlib.use("module://ipympl.backend_nbagg")
plt.ion()
```

**Comment by nvaytet** [comment]
> It looks you aren't actually using ipympl 0.9.7 at runtime, even though that version is installed.

Doing
```
import ipympl

ipympl.__version__
```
in the same notebook does yield `0.9.7`... 🤔

**Comment by nvaytet** [comment]
> I cannot reproduce with the same packages in a new environment:

Can it be the Python version that is different? I can't think of anything else...

**Comment by nvaytet** [comment]
I have now tried this on a different system and I am still getting the same issue: `ipympl==0.9.7` continues to raise the error about buttons with `matplotlib==3.10.3`.

**Comment by ianhi** [comment]
I tried to replicate your envinronment with conda on macos and was unable to replicate

**Comment by HojinCho** [comment]
> [@nvaytet](https://github.com/nvaytet) what OS were you on? And did you also install via conda?
> 
> [@HojinCho](https://github.com/HojinCho) can you please try a debugging step for me by installing with pip instead of conda

Can confirm, matplotlib 3.10.1 and ipympl 0.9.7 installed from pip, under Python 3.12.6 from conda-forge, works without the error (linux x86-64). Seems like the conda-forge distribution has a bug.

**Comment by ianhi** [comment]
Thank you @HojinCho one more debugging request. Could you try to installing directly from the tar.gz on pypi (which is how the conda forge build does it).

```
 pip install https://files.pythonhosted.org/packages/39/1b/acd3d481869d614a7acbb831bd9304411eae47b05d7607db989613028788/ipympl-0.9.7.tar.gz
```

and let me know if that works?

**Comment by ianhi** [comment]
Ok! Thank you both for the info. I think it seems that the conda forge build is broken (at least for Linux) I can't test that easily while traveling. But I'll leave myself a reminder to check this on my linux computer when I'm home in a few weeks. In the meantime it seems installing from pip is a workaround, and hopefully anyone with the power to regenerate a conda build (@martinRenou ?) might be able to fix this

**Comment by ameraner** [comment]
I could reproduce this with matplotlib=3.10.6

**Comment by ianhi** [comment]
> But I'll leave myself a reminder to check this on my linux computer when I'm home in a few weeks. In the meantime it seems installing from pip is a workaround,

I did not check :( and while I am once again travelling. this time I do have my linux laptop.


@ameraner is the issue only with conda for you?

**Comment by ameraner** [comment]
I encountered the issue while using Jupyterlab though...

**Comment by nvaytet** [comment]
Very strange: on a new computer, with
```
matplotlib-base                3.10.8        py312he3d6523_0          conda-forge
ipympl                         0.9.8         pyhcf101f3_0             conda-forge
traitlets                      5.14.3        pyhd8ed1ab_1             conda-forge
ipykernel                      7.1.0         pyha191276_0             conda-forge
ipython                        9.9.0         pyh53cf698_0             conda-forge
ipywidgets                     8.1.8         pyhd8ed1ab_0             conda-forge
```
I no longer have the error... 🤔

**Comment by nvaytet** [comment]
Any news here? Thanks 🙏
